name: Download File 2

on:
  workflow_dispatch:
    inputs:
      download_url:
        description: 'Enter the download URL'
        required: true
        type: string
        default: 'https://github.com/2dust/v2rayNG/releases/download/2.1.7/v2rayNG_2.1.7_armeabi-v7a.apk'
jobs:
  download-job:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Create Directory and Download File
        run: |
          mkdir -p Downloaded_Files
          cd Downloaded_Files
          curl -O -L "${{ github.event.inputs.download_url }}"

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add Downloaded_Files/
          git commit -m "Add downloaded file from ${{ github.event.inputs.download_url }}" || echo "No changes to commit"
          git push
